services:
  api:
    build: .
    volumes:
      - .:/usr/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
