services:
  api:
    image: intellicook.recipesearch.api
    build: .
    volumes:
      - .:/usr/app
      - data:/usr/data
    ports:
      - 2505:2505
    env_file:
      - .env
    environment:
      - DOMAIN_DEFAULT_FAISS_INDEX_PATH=/usr/data/faiss.index
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 2605:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  data:
    name: recipesearch_data
  postgres_data:
    name: postgres_data
