# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/faiss_index_thread.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/faiss_index_thread.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/faiss_index_thread.proto\"\x19\n\x17\x46\x61issIndexThreadRequest\"\x91\x01\n\x18\x46\x61issIndexThreadResponse\x12(\n\x04\x61rgs\x18\x01 \x01(\x0b\x32\x15.FaissIndexThreadArgsH\x00\x88\x01\x01\x12\x16\n\x0eis_in_progress\x18\x02 \x01(\x08\x12\x13\n\x0bis_complete\x18\x03 \x01(\x08\x12\x15\n\ris_successful\x18\x04 \x01(\x08\x42\x07\n\x05_args\"B\n\x14\x46\x61issIndexThreadArgs\x12\r\n\x05\x63ount\x18\x01 \x01(\r\x12\r\n\x05model\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\tB\"\xaa\x02\x1fIntelliCook.RecipeSearch.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.faiss_index_thread_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\037IntelliCook.RecipeSearch.Client'
  _globals['_FAISSINDEXTHREADREQUEST']._serialized_start=35
  _globals['_FAISSINDEXTHREADREQUEST']._serialized_end=60
  _globals['_FAISSINDEXTHREADRESPONSE']._serialized_start=63
  _globals['_FAISSINDEXTHREADRESPONSE']._serialized_end=208
  _globals['_FAISSINDEXTHREADARGS']._serialized_start=210
  _globals['_FAISSINDEXTHREADARGS']._serialized_end=276
# @@protoc_insertion_point(module_scope)
