# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/recipe.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/recipe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import recipe_nutrition_pb2 as protos_dot_recipe__nutrition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/recipe.proto\x1a\x1dprotos/recipe_nutrition.proto\"\x1b\n\rRecipeRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\xc7\x01\n\x0eRecipeResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12,\n\x0bingredients\x18\x04 \x03(\x0b\x32\x17.RecipeRecipeIngredient\x12\x12\n\ndirections\x18\x05 \x03(\t\x12\x0c\n\x04tips\x18\x06 \x03(\t\x12\x10\n\x08utensils\x18\x07 \x03(\t\x12#\n\tnutrition\x18\x08 \x01(\x0b\x32\x10.RecipeNutrition\"f\n\x16RecipeRecipeIngredient\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x08quantity\x18\x02 \x01(\x02H\x00\x88\x01\x01\x12\x11\n\x04unit\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x0b\n\t_quantityB\x07\n\x05_unitB\"\xaa\x02\x1fIntelliCook.RecipeSearch.Clientb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.recipe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\037IntelliCook.RecipeSearch.Client'
  _globals['_RECIPEREQUEST']._serialized_start=54
  _globals['_RECIPEREQUEST']._serialized_end=81
  _globals['_RECIPERESPONSE']._serialized_start=84
  _globals['_RECIPERESPONSE']._serialized_end=283
  _globals['_RECIPERECIPEINGREDIENT']._serialized_start=285
  _globals['_RECIPERECIPEINGREDIENT']._serialized_end=387
# @@protoc_insertion_point(module_scope)
