// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IntelliCook.RecipeSearch.Client {

  /// <summary>Holder for reflection information generated from Protos/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3Mvc2VydmljZS5wcm90bxoTcHJvdG9zL2hlYWx0aC5wcm90bxoq",
            "cHJvdG9zL3NlYXJjaF9yZWNpcGVzX2J5X2luZ3JlZGllbnRzLnByb3RvMq4B",
            "ChNSZWNpcGVTZWFyY2hTZXJ2aWNlEi4KCUdldEhlYWx0aBIOLkhlYWx0aFJl",
            "cXVlc3QaDy5IZWFsdGhSZXNwb25zZSIAEmcKGlNlYXJjaFJlY2lwZXNCeUlu",
            "Z3JlZGllbnRzEiIuU2VhcmNoUmVjaXBlc0J5SW5ncmVkaWVudHNSZXF1ZXN0",
            "GiMuU2VhcmNoUmVjaXBlc0J5SW5ncmVkaWVudHNSZXNwb25zZSIAQiKqAh9J",
            "bnRlbGxpQ29vay5SZWNpcGVTZWFyY2guQ2xpZW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IntelliCook.RecipeSearch.Client.HealthReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.SearchRecipesByIngredientsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
