// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IntelliCook.RecipeSearch.Client {

  /// <summary>Holder for reflection information generated from Protos/service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRQcm90b3Mvc2VydmljZS5wcm90bxoTcHJvdG9zL2hlYWx0aC5wcm90bxoT",
            "cHJvdG9zL3JlY2lwZS5wcm90bxoqcHJvdG9zL3NlYXJjaF9yZWNpcGVzX2J5",
            "X2luZ3JlZGllbnRzLnByb3RvGhtwcm90b3Mvc2VhcmNoX3JlY2lwZXMucHJv",
            "dG8aG3Byb3Rvcy9jaGF0X2J5X3JlY2lwZS5wcm90bxoYcHJvdG9zL2FkZF9y",
            "ZWNpcGVzLnByb3RvGh1wcm90b3MvaW5pdF9mYWlzc19pbmRleC5wcm90bxof",
            "cHJvdG9zL2ZhaXNzX2luZGV4X3RocmVhZC5wcm90bxoXcHJvdG9zL3Jlc2V0",
            "X2RhdGEucHJvdG8yrgUKE1JlY2lwZVNlYXJjaFNlcnZpY2USLgoJR2V0SGVh",
            "bHRoEg4uSGVhbHRoUmVxdWVzdBoPLkhlYWx0aFJlc3BvbnNlIgASLgoJR2V0",
            "UmVjaXBlEg4uUmVjaXBlUmVxdWVzdBoPLlJlY2lwZVJlc3BvbnNlIgASZwoa",
            "U2VhcmNoUmVjaXBlc0J5SW5ncmVkaWVudHMSIi5TZWFyY2hSZWNpcGVzQnlJ",
            "bmdyZWRpZW50c1JlcXVlc3QaIy5TZWFyY2hSZWNpcGVzQnlJbmdyZWRpZW50",
            "c1Jlc3BvbnNlIgASQAoNU2VhcmNoUmVjaXBlcxIVLlNlYXJjaFJlY2lwZXNS",
            "ZXF1ZXN0GhYuU2VhcmNoUmVjaXBlc1Jlc3BvbnNlIgASPQoMQ2hhdEJ5UmVj",
            "aXBlEhQuQ2hhdEJ5UmVjaXBlUmVxdWVzdBoVLkNoYXRCeVJlY2lwZVJlc3Bv",
            "bnNlIgASSwoSQ2hhdEJ5UmVjaXBlU3RyZWFtEhQuQ2hhdEJ5UmVjaXBlUmVx",
            "dWVzdBobLkNoYXRCeVJlY2lwZVN0cmVhbVJlc3BvbnNlIgAwARI3CgpBZGRS",
            "ZWNpcGVzEhIuQWRkUmVjaXBlc1JlcXVlc3QaEy5BZGRSZWNpcGVzUmVzcG9u",
            "c2UiABJDCg5Jbml0RmFpc3NJbmRleBIWLkluaXRGYWlzc0luZGV4UmVxdWVz",
            "dBoXLkluaXRGYWlzc0luZGV4UmVzcG9uc2UiABJMChNHZXRGYWlzc0luZGV4",
            "VGhyZWFkEhguRmFpc3NJbmRleFRocmVhZFJlcXVlc3QaGS5GYWlzc0luZGV4",
            "VGhyZWFkUmVzcG9uc2UiABI0CglSZXNldERhdGESES5SZXNldERhdGFSZXF1",
            "ZXN0GhIuUmVzZXREYXRhUmVzcG9uc2UiAEIiqgIfSW50ZWxsaUNvb2suUmVj",
            "aXBlU2VhcmNoLkNsaWVudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::IntelliCook.RecipeSearch.Client.HealthReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.RecipeReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.SearchRecipesByIngredientsReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.SearchRecipesReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.ChatByRecipeReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.AddRecipesReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.InitFaissIndexReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.FaissIndexThreadReflection.Descriptor, global::IntelliCook.RecipeSearch.Client.ResetDataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
