// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/user_profile_veggie_identity.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace IntelliCook.RecipeSearch.Client {

  /// <summary>Holder for reflection information generated from Protos/user_profile_veggie_identity.proto</summary>
  public static partial class UserProfileVeggieIdentityReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/user_profile_veggie_identity.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UserProfileVeggieIdentityReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CilQcm90b3MvdXNlcl9wcm9maWxlX3ZlZ2dpZV9pZGVudGl0eS5wcm90byqX",
            "AQoZVXNlclByb2ZpbGVWZWdnaWVJZGVudGl0eRIlCiFVU0VSX1BST0ZJTEVf",
            "VkVHR0lFX0lERU5USVRZX05PTkUQABIrCidVU0VSX1BST0ZJTEVfVkVHR0lF",
            "X0lERU5USVRZX1ZFR0VUQVJJQU4QARImCiJVU0VSX1BST0ZJTEVfVkVHR0lF",
            "X0lERU5USVRZX1ZFR0FOEAJCIqoCH0ludGVsbGlDb29rLlJlY2lwZVNlYXJj",
            "aC5DbGllbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::IntelliCook.RecipeSearch.Client.UserProfileVeggieIdentity), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum UserProfileVeggieIdentity {
    [pbr::OriginalName("USER_PROFILE_VEGGIE_IDENTITY_NONE")] None = 0,
    [pbr::OriginalName("USER_PROFILE_VEGGIE_IDENTITY_VEGETARIAN")] Vegetarian = 1,
    [pbr::OriginalName("USER_PROFILE_VEGGIE_IDENTITY_VEGAN")] Vegan = 2,
  }

  #endregion

}

#endregion Designer generated code
