"""Add Recipe

Revision ID: d83569a60f19
Revises:
Create Date: 2024-10-21 19:30:29.937227

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d83569a60f19"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipe",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ingredients", sa.PickleType(), nullable=False),
        sa.Column("instructions", sa.PickleType(), nullable=False),
        sa.Column("raw", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recipe", schema="public")
    # ### end Alembic commands ###
